# Generated by Django 6.0 on 2026-01-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_stt', models.DateField(blank=True, null=True)),
                ('tanggal_masuk_stt', models.DateField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('no_resi', models.CharField(max_length=100, unique=True, verbose_name='No Resi')),
                ('tujuan', models.CharField(blank=True, max_length=100, null=True)),
                ('koli', models.IntegerField(default=0)),
                ('kilo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tanggal_dooring', models.DateField(blank=True, null=True)),
                ('tanggal_kembali', models.DateField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tarif_per_kg', models.CharField(blank=True, max_length=100, null=True)),
                ('total_biaya', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Total (Rp)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transaksi Inbound',
                'verbose_name_plural': 'Daftar Inbound',
                'ordering': ['-tanggal_masuk_stt'],
            },
        ),
        migrations.CreateModel(
            name='OutboundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(blank=True, null=True, verbose_name='Tanggal')),
                ('pengirim', models.CharField(blank=True, max_length=200, null=True)),
                ('penerima', models.CharField(blank=True, max_length=200, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=50, null=True)),
                ('no_resi_bmm', models.CharField(max_length=100, unique=True, verbose_name='No Resi BMM')),
                ('koli', models.IntegerField(default=0)),
                ('kg', models.CharField(blank=True, max_length=50, null=True)),
                ('tarif', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Total (Rp)')),
                ('vendor1_tgl', models.DateField(blank=True, null=True)),
                ('vendor1_resi', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor1_biaya', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('vendor2_tgl', models.DateField(blank=True, null=True)),
                ('vendor2_resi', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor2_biaya', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_bayar', models.DateField(blank=True, null=True)),
                ('nama_bayar', models.CharField(blank=True, max_length=100, null=True)),
                ('profit', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transaksi Outbound',
                'verbose_name_plural': 'Daftar Outbound',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Penerimaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('keterangan', models.CharField(max_length=255)),
                ('nilai', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('saldo', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Penerimaan',
                'verbose_name_plural': 'Daftar Penerimaan',
                'ordering': ['tanggal'],
            },
        ),
    ]
