# Generated by Django 6.0 on 2026-01-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_inboundtransaction_outboundtransaction_penerimaan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('HULU', 'Hulu'), ('KETAPANG', 'Ketapang'), ('PANTURA', 'Pantura'), ('PUTUSSIBAU', 'Putussibau'), ('TRUK', 'Truk'), ('KALTENG', 'Kalteng')], default='HULU', max_length=50)),
                ('tanggal_kirim', models.DateField(blank=True, null=True)),
                ('no_resi', models.CharField(max_length=100)),
                ('pengirim', models.CharField(blank=True, max_length=200, null=True)),
                ('tujuan', models.CharField(blank=True, max_length=200, null=True)),
                ('koli', models.IntegerField(default=0)),
                ('kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('penerima', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal_terima', models.DateField(blank=True, null=True)),
                ('tarif', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Total Hutang (Rp)')),
                ('status_bayar', models.BooleanField(default=False, verbose_name='Sudah Dibayar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Manifest',
                'verbose_name_plural': 'Daftar Manifest',
                'ordering': ['-tanggal_kirim', 'kategori'],
                'unique_together': {('no_resi', 'kategori')},
            },
        ),
    ]
