# Generated by Django 6.0 on 2026-01-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_manifest'),
    ]

    operations = [
        migrations.CreateModel(
            name='KasHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('keterangan', models.CharField(max_length=255)),
                ('jenis', models.CharField(choices=[('MASUK', 'Kas Masuk'), ('KELUAR', 'Kas Keluar')], default='KELUAR', max_length=10)),
                ('debit', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Debit (Masuk)')),
                ('kredit', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Kredit (Keluar)')),
                ('saldo', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kas Harian',
                'verbose_name_plural': 'Kas Harian',
                'ordering': ['tanggal', 'created_at'],
            },
        ),
        migrations.AlterField(
            model_name='akun',
            name='kategori',
            field=models.CharField(choices=[('ASSET', 'Harta (Aktiva)'), ('LIABILITY', 'Kewajiban (Utang)'), ('EQUITY', 'Modal (Ekuitas)'), ('REVENUE', 'Pendapatan'), ('EXPENSE', 'Biaya')], max_length=20),
        ),
        migrations.AlterField(
            model_name='akun',
            name='nama',
            field=models.CharField(help_text='Contoh: Kas, Modal, Biaya Gaji', max_length=100),
        ),
    ]
