# Generated by Django 6.0 on 2026-01-08 08:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_kasharian_alter_akun_kategori_alter_akun_nama'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_invoice', models.CharField(max_length=50, unique=True)),
                ('customer', models.CharField(max_length=100)),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('jatuh_tempo', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('status', models.CharField(default='BELUM BAYAR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-tanggal', '-no_invoice'],
            },
        ),
        migrations.AddField(
            model_name='inboundtransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_items', to='finance.invoicetagihan'),
        ),
    ]
