# Generated by Django 6.0 on 2026-01-08 10:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_invoicetagihan_inboundtransaction_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('posisi', models.CharField(blank=True, max_length=100, null=True)),
                ('gaji_pokok', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('no_hp', models.CharField(blank=True, max_length=20, null=True)),
                ('tanggal_masuk', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cashbon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('nominal', models.DecimalField(decimal_places=0, max_digits=15)),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashbons', to='finance.karyawan')),
            ],
            options={
                'verbose_name': 'Cashbon',
                'verbose_name_plural': 'Daftar Cashbon',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Penggajian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.IntegerField()),
                ('tahun', models.IntegerField()),
                ('tanggal_gaji', models.DateField(default=django.utils.timezone.now)),
                ('gaji_pokok', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('lembur', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('bonus', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('potongan_cashbon', models.DecimalField(decimal_places=0, default=0, help_text='Total Cashbon periode ini', max_digits=15)),
                ('potongan_absen', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('potongan_bpjs', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('potongan_lain', models.DecimalField(decimal_places=0, default=0, help_text='Hutang Cafe/Kantin dll', max_digits=15)),
                ('total_diterima', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PAID', 'Sudah Dibayar')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penggajian', to='finance.karyawan')),
            ],
            options={
                'verbose_name': 'Slip Gaji',
                'verbose_name_plural': 'Data Penggajian',
                'ordering': ['-tahun', '-bulan', 'karyawan'],
                'unique_together': {('karyawan', 'bulan', 'tahun')},
            },
        ),
    ]
