# Generated by Django 6.0 on 2026-01-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_karyawan_cashbon_penggajian'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='dp',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Biaya Dibayar Dimuka (DP)'),
        ),
    ]
