# Generated by Django 6.0 on 2026-01-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_manifest_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetagihan',
            name='biaya_awb',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Biaya Kirim AWB'),
        ),
    ]
