# Generated by Django 6.0.4 on 2026-04-09 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_invoicetagihan_biaya_handling'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsInbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_resi', models.CharField(help_text='Nomor resi unik', max_length=50, unique=True)),
                ('tanggal', models.DateField(help_text='Tanggal barang diterima')),
                ('pengirim', models.CharField(help_text='Nama pengirim', max_length=150)),
                ('penerima', models.CharField(help_text='Nama penerima', max_length=150)),
                ('asal', models.CharField(help_text='Kota / lokasi asal', max_length=100)),
                ('tujuan', models.CharField(help_text='Kota / lokasi tujuan', max_length=100)),
                ('berat', models.DecimalField(decimal_places=2, help_text='Berat dalam Kg', max_digits=10)),
                ('keterangan', models.TextField(blank=True, default='', help_text='Catatan tambahan (opsional)')),
                ('status', models.CharField(choices=[('DITERIMA', 'Diterima di Gudang'), ('PROSES', 'Sedang Diproses'), ('SIAP_KIRIM', 'Siap Kirim'), ('DIKIRIM', 'Sudah Dikirim')], default='DITERIMA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Inbound (Barang Masuk)',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpsManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_manifest', models.CharField(help_text='Nomor manifest unik', max_length=50, unique=True)),
                ('tanggal', models.DateField(help_text='Tanggal keberangkatan')),
                ('armada', models.CharField(help_text='Nama armada / kendaraan / ekspedisi', max_length=100)),
                ('rute', models.CharField(help_text='Rute pengiriman (misal: Jakarta → Surabaya)', max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('BERANGKAT', 'Sedang Dalam Perjalanan'), ('SAMPAI', 'Sudah Sampai')], default='DRAFT', max_length=20)),
                ('catatan', models.TextField(blank=True, default='', help_text='Catatan tambahan (opsional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Manifest Pengiriman',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpsOutbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(help_text='Tanggal barang dikeluarkan')),
                ('catatan', models.TextField(blank=True, default='', help_text='Catatan tambahan (opsional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inbound', models.OneToOneField(help_text='Barang dari Inbound yang akan dikirim', on_delete=django.db.models.deletion.CASCADE, related_name='outbound', to='finance.opsinbound')),
                ('manifest', models.ForeignKey(help_text='Manifest pengiriman tempat barang ini dimuat', on_delete=django.db.models.deletion.CASCADE, related_name='outbound_items', to='finance.opsmanifest')),
            ],
            options={
                'verbose_name_plural': 'Outbound (Barang Keluar)',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
    ]
