# Generated by Django 6.0.4 on 2026-04-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_opsinbound_opsmanifest_opsoutbound'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsinbound',
            name='tarif_per_kg',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='opsinbound',
            name='total_biaya',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='opsinbound',
            name='vendor',
            field=models.CharField(blank=True, help_text='Vendor pengirim (untuk Akuntansi)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opsmanifest',
            name='dp',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Uang Panjar / DP', max_digits=15),
        ),
        migrations.AddField(
            model_name='opsmanifest',
            name='total_hutang',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='opsmanifest',
            name='vendor_penerima',
            field=models.CharField(blank=True, help_text='Nama Vendor / Penerima Manifest', max_length=150, null=True),
        ),
    ]
