# Generated by Django 6.0.4 on 2026-04-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_opsinbound_tarif_per_kg_opsinbound_total_biaya_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='armada_ops',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='nomor_manifest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='rute_ops',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
