# Generated by Django 6.0.4 on 2026-05-26 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_manifest_armada_ops_manifest_nomor_manifest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='armada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='catatan_ops',
            field=models.TextField(blank=True, db_column='catatan', null=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='rute',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='tanggal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Nama Model')),
                ('object_id', models.CharField(max_length=50, verbose_name='ID Objek')),
                ('object_repr', models.CharField(max_length=255, verbose_name='Representasi Objek')),
                ('action', models.CharField(choices=[('CREATE', 'Tambah Data'), ('UPDATE', 'Ubah Data'), ('DELETE', 'Hapus Data')], max_length=10, verbose_name='Aksi')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Detail Perubahan')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='finance_aud_timesta_05877e_idx'), models.Index(fields=['model_name', '-timestamp'], name='finance_aud_model_n_38a528_idx'), models.Index(fields=['user', '-timestamp'], name='finance_aud_user_id_006604_idx')],
            },
        ),
    ]
