# Generated by Django 6.0.5 on 2026-06-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_manifest_armada_manifest_catatan_ops_manifest_rute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='block_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash Block'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='block_index',
            field=models.IntegerField(default=1, verbose_name='Nomor Block'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='previous_hash',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64, verbose_name='Hash Sebelumnya'),
        ),
    ]
