# Generated by Django 6.0.4 on 2026-06-05 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_auditlog_block_hash_auditlog_block_index_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['block_index'], name='finance_aud_block_i_9be327_idx'),
        ),
    ]
